#!/usr/bin/env python3
import requests
import json

prompt = "Watch my Google Sheet for rows where sales are above 5000, then send Slack alert, SMS via Twilio, and log the alert"

print(f"Testing with prompt: {prompt}\n")

# Test mock server directly
resp = requests.post('http://127.0.0.1:8000/generate', json={'prompt': prompt}, timeout=10)
workflow = resp.json()['workflow']

print("Nodes generated by mock server:")
for node in workflow['nodes']:
    print(f"  - {node['name']} ({node['type'].split('.')[-1]})")

print(f"\nTotal nodes: {len(workflow['nodes'])}")
